CREATE TABLE seller (
                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name       VARCHAR(100) NOT NULL,
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
);

INSERT INTO seller (name, created_at, updated_at)
SELECT '판매자-' || gs, now(), now() FROM generate_series(1, 1000) gs;
ALTER TABLE item ADD COLUMN seller_id BIGINT REFERENCES seller (id);
UPDATE item SET seller_id = (id - 1) % 1000 + 1;
ALTER TABLE item ALTER COLUMN seller_id SET NOT NULL;