CREATE TABLE daily_sales_summary (
                                     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     sales_date     DATE      NOT NULL,
                                     seller_id      BIGINT    NOT NULL,
                                     order_count    INT       NOT NULL DEFAULT 0,   -- 결제완료 주문 수
                                     item_quantity  INT       NOT NULL DEFAULT 0,   -- 판매 수량
                                     sales_amount   BIGINT    NOT NULL DEFAULT 0,   -- 결제완료 매출액
                                     cancel_count   INT       NOT NULL DEFAULT 0,   -- 취소 주문 수
                                     cancel_amount  BIGINT    NOT NULL DEFAULT 0,   -- 취소 금액
                                     created_at     TIMESTAMP NOT NULL DEFAULT now(),
                                     updated_at     TIMESTAMP NOT NULL DEFAULT now(),
                                     CONSTRAINT uk_daily_sales_seller_date UNIQUE (seller_id, sales_date)
);

CREATE INDEX idx_daily_sales_date ON daily_sales_summary (sales_date);